before_install:
  - gem update bundler rake
cache: bundler
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - "2.5"
  - "2.6"
  - "2.7"
  - ruby-head
script: bundle exec rspec
sudo: false
